# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.2
language: objective-c
cache: cocoapods
install:
  - bundle install
  - cd Example && bundle exec pod install
script:
  - bundle exec rake ci
# This causes builds for merges and direct pushes to master.
# Other branches are pull requests and build are triggered via the
# pull request hook
branches:
  only:
    - master
