# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

# $MAIN_STAGE is used to selectively run only certain steps on the
# latest iOS version. For example snapshot tests are only ran for the
# latest version.
osx_image: xcode12
language: objective-c
cache:
  cocoapods: true
  bundler: true
  directories:
    - node_modules
matrix:
  include:
    - osx_image: xcode12
      env: SWIFT=5.0 BUILD_SDK=iphonesimulator14.0 DESTINATION="OS=14.0,platform=iOS Simulator,name=iPhone 8" FULL_TESTS="true" MAIN_STAGE="true"
    - osx_image: xcode12
      env: SWIFT=4.2 BUILD_SDK=iphonesimulator14.0 DESTINATION="OS=13.5,platform=iOS Simulator,name=iPhone 8" FULL_TESTS="false" MAIN_STAGE="false"
before_install:
  - sudo sntp -sS time.apple.com
  - brew install clang-format
  - nvm install
  - nvm use
  - 'if [[ "$MAIN_STAGE" = true ]]; then npm install -g greenkeeper-lockfile@1; fi'
install:
  # If a different version of bundler has been used, CI will fail with a very unhelpful error message at `bundle install`.
  # This is hopefully somewhat more helpful:
  - if [[ $(cat Gemfile.lock | sed -n '/BUNDLED WITH/{n;p;}' | sed '/^$/d;s/[[:blank:]]//g') != "2.1.4" ]]; then echo "Error - Gemfile.lock should be bundled with bundler 2.1.4"; exit 64; fi
  - npm install
  - gem install bundler --version 2.1.4
  - bundle install
  - (cd Example && bundle exec pod install)
before_script: 'if [[ "$MAIN_STAGE" = true ]]; then greenkeeper-lockfile-update; fi'
script:
  - npm run build
  - 'if [[ "$MAIN_STAGE" = true ]]; then danger; fi'
  - 'if [[ "$MAIN_STAGE" = true ]]; then ./scripts/check-pristine-state package-lock.json; fi'
  - 'if [[ "$MAIN_STAGE" = true ]]; then (cd Example && Pods/SwiftLint/swiftlint lint --strict --config .swiftlint.yml); fi'
  - 'if [[ "$MAIN_STAGE" = true && ! -n "$TRAVIS_TAG" ]]; then ./scripts/build-docs-ci && rm -rf docs; fi'
  - 'if [[ "$MAIN_STAGE" = true && -n "$TRAVIS_TAG" ]]; then ./scripts/build-docs-ci $TRAVIS_TAG; fi'
  - (cd Example && bundle exec rake ci)
after_script:
  - 'if [[ "$MAIN_STAGE" = true ]]; then greenkeeper-lockfile-upload; fi'
  - 'if [ "$MAIN_STAGE" == true ] && [ "$TRAVIS_BRANCH" == master ] && [ "$TRAVIS_PULL_REQUEST" == false ]; then curl -s -X POST -H "Content-Type: application/json" -H "Accept: application/json" -H "Travis-API-Version: 3" -H "Authorization: token $TRAVIS_API_KEY" -d "{\"request\": {\"branch\":\"master\"}}" https://api.travis-ci.org/repo/Skyscanner%2Fbackpack-docs/requests; fi'
branches:
  only:
    - master
    - /^greenkeeper/.*$/
    - /^[0-9]+\.[0-9]+\.[0-9]+$/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $IOS_DOCS_DEPLOY_TOKEN
  on:
    tags: true
    all_branches: true
    condition: "$MAIN_STAGE = true"
  local_dir: docs/
  skip_cleanup: true
  detect_encoding: true
  repo: backpack/ios
  target-branch: master
  verbose: true
  keep-history: true

env:
  global:
    - secure: qKO1dhfy5WsvI1bIeTLA+V89DoYd2HzbNJ72mK71FF/vEewfDOyxDA7TbBc4ogwpKZv8YZdIahDZe+BdR12ICm5h5J3sV7uqVAm1TnJr79k+G/YfrNtevAxfv1Ja9oYed7brqz8MkxtzM4An8o9ncmV1T9fDxJExyDvWGF6YkN46QXuz7wBg7jrRZ/P/WAvrdYXtisXjhMQjWQOzgF/6DKhexGHirrE/IE26AmJA3akSbYZn1sQSxQXyzX4cfabewHODEjxtHWWQr97yYvmKY2bCRbFN+IxPY7/wFCjKv9IKePKs4tajlwsj7gknxJC7PqdJOqjSGSFvbm98WJ66dFKzZbQpYaGz3v87w6EmcQp7xaKjmcqThDGHtKSPLtppKedFki0wAkZSQyE+vnqVV2eCpY8JLqweoPIaXw3eHDU7Q/4xqSXzb7sMCEu3l4W2DQ/ZanRQkQwlwslleAK+QHyFfnOkGYJWr2EoB3kLqIbgyvEn8+LOH6GhFOR5Z9Rh2REAqCXgWCEMRaIycDigJS+9OCxZlpP740EtqCQsASKx/cEoz8lbEGA6bQWGyjbGE5XsSDx6gMUszIDMK+e48KqKatLosMkPDM1hyGVwxyRf8bh7Ske8NIfJ0Whw667Qo/5UWMtC9OiG9NZ+iSLbur9Gtq/X7MEZDaM6Y5BnB2w=
