# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.2
language: objective-c
cache: cocoapods
install:
  - cd Example && bundle exec pod install
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/Backpack.xcworkspace -scheme Backpack-Example -sdk iphonesimulator11.2 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
